### ISSUE TITLE
I know it's still early days, but none of the addons seem to install properly with the DX11 Beta

### ISSUE THREAD

**Issue by Moraxan** [gw2-addon-loader/GW2-Addon-Manager#127]
As stated in the topic.
The game installs the addons and I get proper folders. 
The addons aren't however accessible in game.
A fair guess here would be that they need to hook into another dx-engine and not the dx9 as they've done so far.

**Comment by unrelentingsarcasm** [comment]
I haven't initiated use of the DX11 beta yet on my GW2 so my issue may be worth moving to a new topic, although it started with the update that included DX11.

I use Launchbuddy v2.4.1, UOAOM v1.3.0, GW2Hook v1.2.0, d912pxy v2.4.4 r696, and GW2Radial v2.1.0-pre1 (I realize this isn't the . I use Launchbuddy to load multiple instances of the game and to inject the d912pxy and GW2Hook Reshade64.dll.  I use UOAOM primarily to load GW2Radial and Arc with the custom UOAOM wrapper as there doesn't seem to be a plausible alternative that allows me to load all 4 of those addons in multiple instances.  Because that version of Radial is not the current one UOAOM uses, I downloaded it from FriendlyFire's GitHub, renamed it to gw2addon_gw2radial.dll and placed it in the addon/gw2radial folder where UOAOM's wrapper calls from.

The game played fine yesterday following the update after disabling the UOAOM d3d9.dll in the bin64 folder, which I did because I assume it was trying to load an older version of Arc that was not compatible with the new release.  So fine, in fact, that I did not experience a single client crash like most of the community did yesterday.  Today on reactivation of UOAOM's d3d9.dll and updating Arc and GW2Radial (this extension didn't update as there hasn't been a new release) through UOAOM, my game repeatedly crashes on start up.  The UOAOM log does not update as if it is not starting when the game launches.  Furthermore, I downloaded the latest Arc update on my own and inject it with Launchbuddy,and  I have no issue in starting the game or using Arc, but I do lose GW2Radial which I was getting from UOAOM.  To me it appears the GW2 update is not loading the UOAOM d3d9.dll which may be related to their inclusion of the DX11 coding, even though I have not selected to use DX11 in the in-game menu option.

**Comment by TrYkeRm4N** [comment]
Im afraid that dev of the addon-loader doesn't play Gw2 anymore, so we're orphans now.

I see he doesnt contribute since march so probably he's out. Anyway his past contributions work for so long that we should thank him the job until dx11 rollout.

**Comment by unrelentingsarcasm** [comment]
Under the credits section of the wiki, it appears he states that he no longer owns this project as of Sep 8 2021, but the page editor says he edited it because of "new ownership" so hopefully this project got passed on to someone who still intends to keep it alive.  Maybe @megai2 and @Archomeda.

**Comment by unrelentingsarcasm** [comment]
UPDATE:

To the issue I posted about in the reply, it seems that as long as I move the UOAOM d3d9.dll file out of the bin64 folder and inject it as the prime extension (injected before it attempts to inject d912pxy or GW2Hook) with Launchbuddy, all of it works with no problem.  This is extremely convoluted solution.

**Comment by TristisOris** [comment]
looks we should back to manual addons update(
arcdps didnt work from this installation. files must be renamed.

**Comment by Jarelk** [comment]
Someone could fork it and make their own fix, but I admit I'm a bit too lazy to do it.

**Comment by megai2** [comment]
DX11 support is here in latest CI builds

**Comment by IanBFarrell** [comment]
I installed today with 1.4.0 alpha and the addons still are not loaded. Any thoughts? I tried Force Redownload and Reset to Clean Install but neither worked. I even deleted the d3d files.

Thanks

**Comment by Friendly0Fire** [comment]
None of the addons have been updated and it'll take a while for some of them. Please track each addon's progress towards DX11 support on their respective issue trackers, thank you!
