### ISSUE TITLE
"Unable to initialize 3D output" after installing anything with Addon Manager

### ISSUE THREAD

**Issue by CamdenQ** [gw2-addon-loader/GW2-Addon-Manager#144]
### Please attach a copy of config.yaml or config.ini to the issue.
I don't know where to find this. God forbid you include instructions on where it should be located. The only file named config I could find is the config.xml file in the GW2 Addon Manager's directory, which I can't attach.

**Describe the bug**
I reported this issue [here](https://github.com/gw2-addon-loader/GW2-Addon-Manager/issues/122) with multiple other people responding with the same issue, and it was closed without explanation. Terrible user support.

From that issue, because nothing has changed: 

> 
> Like the title says, no matter what I install, not just the DirectX 12 proxy, I get this:
> ![image](https://user-images.githubusercontent.com/23227790/135195170-1a62d70e-0e8f-4487-a1f5-e215ce77d50f.png)
> 
> 
> My GPU supports DirectX 12, my drivers are up to date, and I reinstalled the GPU drivers and DirectX 12 just to be safe. Nothing changes.
> 
> The only way I've found to fix the issue once I get that error is to delete my bin64 folder. None of the actions available in the manager fix it.

**To Reproduce**
List steps to reproduce the bug, if possible.
1. Launch GW2 Addon Manager
2. Install literally any addon on the list
3. Try to run game
4. Above error is returned

**Additional context**

Don't close issues that are not resolved without even giving a reason. That is not how you support a project

**don't forget to attach the config file to the issue**

**Comment by Friendly0Fire** [comment]
Terribly sorry you feel the "user support" experience for this free project ran by volunteers in their personal time is not up to your standards. Until a few days ago, nobody was maintaining this project, maybe you preferred that?

Unfortunately for you, this issue does not appear to be related to the addon manager. This, plus its age, is why it was closed. Feel free to open an issue on the addon loader repository or the d912pxy one (though good luck there seeing as it's been deprecated).

**Comment by xivor** [comment]
The OP should consider what might possibly be wrong with his GW2 installation, because that is a GW2 error. I wouldn't blame the mods, because if you have to delete BIN64, then you are deleting the GW2 system files, which are likely rebuilt by running the program again.

Also, you might want to verify that you have DirectX9 (not DirectX12).  I understand that your GPU supports DX12, but GW2 uses DX9, and the game cannot be run without it.  In fact, I believe even the DX11beta still requires DX9 at the moment.

So my recommendation is to cleanly uninstall all mods.  Delete the Addons folder and the d3d9.dll in bin64, and d3d11/dxgi.dll in the root if they exist, and addonloader.dll in the root. Remove the mods and the AddonManger from the equation and see if the issue persists.  If it does, then you are barking up the wrong tree and should do a Guild Wars repair.

If it works, then you should attach the AddonManager log, gw2al_log.txt in the GW2 root. Here is an example: 
![image](https://user-images.githubusercontent.com/43550443/135261913-6a1b021e-6223-46a1-855b-1f82dc5a749d.png)

You can always ask for assistance as well on the Discord for the GW2 Development Community.  I have found not only the developers of this project (and its new maintainer), but also the developers for other associated projects very helpful and very quick to respond.

**Comment by CamdenQ** [comment]
@Friendly0Fire I appreciate that you seem to have taken up this abandoned project and are doing this in your free time. However, that's not super useful in terms of issue reporting if you give zero support or feedback. I don't think it's too much to ask that you give a reason when you close an issue that multiple users are experiencing.

The issue was less than two months old, was also being experienced by at least two other users, and only occurs when installing addons with the addon manager, so I don't know how you've come to the conclusion that it has nothing to do with the addon manager.

The issue is definitely NOT d912pxy, because it works fine when I install it manually, and I explicitly stated that this happens regardless of which addon I install. ArcDPS and your own GW2Radial also kick out this same exact error when installed with the Addon Manager.

If you could possibly give some context as to why this is supposedly the addon loader's fault, or where I could even find that repo, that would be helpful.

@xivor I appreciate that unlike Friendly0Fire you're actually considering the issue critically and expanding upon your thought process, rather than dismissing it out of hand for no discernable reason.

Technically, I have figured out since posting that I only have to delete the d3d9.dll added by the manager. Also, as I thought I made clear in the description but perhaps I could have been more clear, the game runs perfectly without addons, and fixing the issue by deleting bin64 restores the game to working order. This would be with d9. I have not opted into the d11 beta for more than a few minutes before turning it back off.

The issue does not persist even just deleting the bin64, so I don't know why you think it might persist if I remove everything. I don't say this to be glib. I'm honestly curious what that would change.

I have tried from clean GW2 installations, and the game runs fine normally, but the second I install any single addon with GW2 Addon Manager, the game breaks with the above error. I will attach my gw2al_log.txt from my most recent attempt installing addons to a clean GW2 install, but there's very little in it.

To be clear, I can manually install GW2Radial, ArcDPS, and d912pxy together and everything works great. None of these addons are breaking anything in and of themselves.

It seems to me that there's an issue with the d3d9.dll file being created by this program or how it's being read, which is throwing an error in DirectX9 and causing GW2 to crash.

[gw2al_log.txt](https://github.com/gw2-addon-loader/GW2-Addon-Manager/files/7253927/gw2al_log.txt)
l.

**Comment by xivor** [comment]
THis is what my log file looks like in a DX9 configuration:
![image](https://user-images.githubusercontent.com/43550443/135349223-1283d703-0e7a-4982-a627-0884330133a9.png)
Does your GW2 root installation have this:
![image](https://user-images.githubusercontent.com/43550443/135349488-7614b66c-691b-4420-a527-a8022a7b0459.png)
Does your addons folder have this:
![image](https://user-images.githubusercontent.com/43550443/135349598-2709c4e0-8ad2-4d1a-b5c0-eea6fb4110e8.png)
Which contains this:
![image](https://user-images.githubusercontent.com/43550443/135349660-6cd2993c-ef29-47dd-bdb6-dfe5973e4916.png)
And of course, do you have this if you are using arcDPS:
![image](https://user-images.githubusercontent.com/43550443/135349754-aea36931-f2fb-40e2-8345-fd4b5809f867.png)
Which contains this:
![image](https://user-images.githubusercontent.com/43550443/135349812-e54e0a97-8b12-4045-8899-a9be71d01f89.png)

If missing any of these, I would do the following, which has helped me in the past. Heck, I would do this ANYWAY, because it ensures a complete installation of the entire AddonManager and mods (from as far as I can tell):
![image](https://user-images.githubusercontent.com/43550443/135349335-6c657f59-74f5-42b1-a7ae-85ec0f5d33a8.png)
When trying to test things and uninstalling and reinstalling mods, I have made mistakes where files were deleted or still there when I didnt want them, and this always seemed to fix the problem for me.
